export enum ConcurrencyTag {
  AMPLA_CONCORRENCIA = "AMPLA_CONCORRENCIA",
  ESCOLA_PUBLICA = "ESCOLA_PUBLICA",
  BAIXA_RENDA = "BAIXA_RENDA",
  PPI = "PPI", // Pretos, Pardos e Indígenas (Combo)
  PRETOS_E_PARDOS = "PRETOS E PARDOS", // New valid tag
  INDIGENAS = "INDIGENAS",
  QUILOMBOLAS = "QUILOMBOLAS",
  PCD = "PCD",
  TRANS = "TRANS",
  RURAL = "RURAL",
  AGRICULTURA_FAMILIAR = "AGRICULTURA_FAMILIAR",
  REFUGIADOS = "REFUGIADOS",
  CIGANOS = "CIGANOS",
  AUTISMO = "AUTISMO",
  ALTAS_HABILIDADES = "ALTAS_HABILIDADES",
  // Academic/Professional Status
  NAO_GRADUACAO = "NAO_GRADUACAO",
  EJA_ENCCEJA = "EJA_ENCCEJA",
  PROFESSOR = "PROFESSOR",
  MILITAR = "MILITAR",
  EFA = "EFA", // Escolas Família Agrícola
  PRIVACAO_LIBERDADE = "PRIVACAO_LIBERDADE",
  // Income specific
  RENDA_ATE_1_SM = "RENDA_ATE_1_SM",
  RENDA_ATE_1_5_SM = "RENDA_ATE_1_5_SM",
  RENDA_ATE_2_SM = "RENDA_ATE_2_SM",
  RENDA_ATE_4_SM = "RENDA_ATE_4_SM",
  SEM_CRITERIO_RENDA = "SEM_CRITERIO_RENDA",
  // Specific / Other
  PCD_AUDITIVA = "PCD_AUDITIVA",
  ESCOLA_PRIVADA_BOLSA_INTEGRAL = "ESCOLA_PRIVADA_BOLSA_INTEGRAL",
  OUTROS_ESPECIFICO = "OUTROS_ESPECIFICO",
}
