name: gitleaks
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Gitleaks
        run: |
          VERSION="8.27.2"
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -xzf gitleaks_${VERSION}_linux_x64.tar.gz
          sudo install gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks
        run: gitleaks detect --source . -v --redact
